name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'master'
      - '[0-9]+.[0-9]+.x'
    tags:

env:
  default_php: 8.0
  stable_php: 8.1


jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x

  test-coverage:

    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: shivammathur/setup-php@2.26.0
        with:
          php-version: ${{ env.stable_php }}
          coverage: pcov
          ini-values: pcov.enabled=1
      - uses: "ramsey/composer-install@2.2.0"
      - run: php ./vendor/bin/phpunit --coverage-clover=coverage.xml
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false
          env_vars: PHP_VERSION

  composer-require-checker:
    name: "Check for missing dependencies"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: shivammathur/setup-php@2.26.0
        with:
          php-version: ${{ env.stable_php }}
          ini-values: memory_limit=-1
          extensions: ${{ env.php_extensions }}
      - uses: "ramsey/composer-install@2.2.0"
      - run: composer global config bin-dir /usr/local/bin
      - run: composer global require -W maglnet/composer-require-checker
      - run: /usr/local/bin/composer-require-checker check
